#!/bin/bash

# Copyright (c) 2021 by Philip Collier, radio AB9IL
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version. There is NO warranty; not even for
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# All credit goes to radio AB9IL. Above is the original Copywright. See how I modified almost nothing from the original script at https://github.com/AB9IL/Skywave-Linux-v4/blob/master/vlc-playlist.

# Needs mpv and fzf to work and for the script to point to the wfmustreams file. Other than that all the work is done by WFMU!

trap wfmu SIGINT

STREAMS_FILE=~/.wfmustreams
OPTION1="1) Start WFMU"
OPTION2="2) Stop Streaming"
OPTION3="3) Edit Stream/Archive List"
OPTIONS="$OPTION1\n$OPTION2\n$OPTION3"
FZF_COMMAND1='fzf --cycle --margin 1,30% --pointer=?? --layout=reverse --header=🐕...w...o...o...f...m...u...🐮'
ROFI_COMMAND1='dmenu -p Select'
FZF_COMMAND2='fzf --cycle --margin 1,30% --pointer=?? --layout=reverse --header=🐕...w...o...o...f...m...u...🐮'
ROFI_COMMAND2='dmenu -p Select'
FZF_COMMAND3="vim $STREAMS_FILE"
ROFI_COMMAND3="x-terminal-emulator -e vim $STREAMS_FILE"

# interface based on commandline arguments
case "$1" in
    gui)
        COMMAND1=$ROFI_COMMAND1
        COMMAND2=$ROFI_COMMAND2
        COMMAND3=$ROFI_COMMAND3
    ;;
    *)
        COMMAND1=$FZF_COMMAND1
        COMMAND2=$FZF_COMMAND2
        COMMAND3=$FZF_COMMAND3
    ;;
esac

start_player(){
stop_player
echo -e 
echo "	              Connecting to "$CHOICE
echo -e 
mpv $URL
    >/dev/null 2>&1 &
exit 0
}

stop_player(){
echo -e 
echo -e "*******************************                       *******************************"
echo -e "🐕...w...o...o...f...m...u...🐮                       🐕...w...o...o...f...m...u...🐮"
echo -e "*******************************                       *******************************"
echo -e 
echo -n "                  archive playlist at "
echo -n "http://www.wfmu.org/playlists/" 
echo -n $URL | awk -F'[=.x]' '{print $2}' | cut -d '/' -f 4
echo -e "                   👓 ******************************************** 👓"
echo -e "                         press Enter for prior week's archive"
echo -e "                               Control-c to search again" 

killall -9 mpv > /dev/null 2>&1
}

# select option from second menu instance
SELECTED="$(echo -e "$OPTIONS" | $COMMAND1 )"

case $SELECTED in
  $OPTION1)
    readarray STREAMS < $STREAMS_FILE
    CHOICE="$(echo "${STREAMS[@]}" | awk -F \" '{print $2}' | $COMMAND2 )"
    [[ -z "$CHOICE" ]] && echo "No selection..." && exit 1
    # find the correct stream url
    i=0
    while [ $i -lt ${#STREAMS[@]} ]; do
        ITEM="$(echo "${STREAMS[i]}" | awk -F \" '{print $2}')"
        [[ "$ITEM" == "$CHOICE" ]] && URL="$(echo "${STREAMS[i]}" | \
            awk -F \" '{print $1}'| sed 's/^ //g')" && start_player
        ((i++))
    done
    ;;
  $OPTION2)
      # cleanly stop the player
      stop_player
    ;;
  $OPTION3)
      # edit the list of streaming stations 
      $COMMAND3
    ;;
esac
